= Integrate AE with Access Management
:page-sidebar: ae_sidebar
:page-permalink: ae/am_installation.html
:page-folder: ae/am
:page-description: Gravitee Alert Engine - Access Management - Installation
:page-toc: true
:page-keywords: Gravitee, API Platform, Alert, Alert Engine, documentation, manual, guide, reference, api
:page-layout: ae
:page-liquid:

== Overview
This page explains how to integrate AE with link:https://www.gravitee.io/products/access-management[Gravitee.io Access Management^] (AM).

If you are performing a new installation of Gravitee.io Enterprise API Platform or running Enterprise
Docker images, you can skip the installation section.

IMPORTANT: To integrate AM with AE, your AM platform must
be an link:/ee/ee_introduction.html[Enterprise version].

== Installation

=== Download connector

[source,bash]
[subs="attributes"]
$ curl -L https://download.gravitee.io/graviteeio-ae/plugins/connectors/gravitee-ae-connectors-ws/gravitee-ae-connectors-ws-{{site.products.ae.version}}.zip -o gravitee-ae-connectors-ws-{{site.products.ae.version}}.zip

=== Install connector

In the command below, ${GRAVITEEIO_HOME} refers to the root directory of both the APIM Gateway and APIM API.

[source,bash]
[subs="attributes"]
$ cp gravitee-ae-connectors-ws-{{site.products.ae.version}}.zip ${GRAVITEEIO_HOME}/plugins/

== Configuration

NOTE: This section will be updated soon.
